# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubSwiftRepos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubSwiftRepos
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  
  target 'GithubSwiftReposTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubSwiftReposUITests' do
    # Pods for testing
  end

end
